version: '2'
services:
    db:
        image: postgres:9.6
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=crc
            - POSTGRES_USER=crc
            - POSTGRES_PASSWORD=crc
    workflow:
        build: ../cr-connect-workflow
        environment:
            - PYTHONPATH=/crc-workflow
        volumes:
            - ../cr-connect-workflow:/crc-workflow
        depends_on:
            - db
        ports:
            - '5000:5000'
    frontend:
        build: ../cr-connect-frontend
        volumes:
            - ../cr-connect-frontend:/crc-frontend
            - /crc-frontend/node_modules
        depends_on:
            - db
        ports:
            - '4200:4200'
    bpmn:
        build: ../cr-connect-bpmn
        volumes:
            - /crc-bpmn
        ports:
            - '5001:80'
        depends_on:
            - db
