version: '2'
services:
    db:
        image: postgres:9.6
        volumes:
            - ./pgdata:/var/lib/postgresql/data
    workflow:
        build: ../cr-connect-workflow
        volumes:
            - ../cr-connect-workflow:/crc-workflow
        depends_on:
            - db
        ports:
            - '5000:5000'
    frontend:
        build: ../cr-connect-frontend
        volumes:
            - ../cr-connect-frontend:/crc-frontend
            - /crc-frontend/node_modules
        depends_on:
            - db
        ports:
            - '4200:4200'
