- name: update packages if the last one is more than a day ago
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: install packages needed for docker and ansible remote docker control
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3
      - python3-pip
      - python-pip

- name: Install docker pip package
  pip:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - docker
      - docker-compose

- name: update packages
  apt:
    update_cache: yes

- name: install docker packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: fix docker sock perms
  file:
    path: /var/run/docker.sock
    mode: '0666'
