---
- hosts: admin
  become: yes
  become_user: root
  tasks:

    - name: set rancher state = started
      import_role:
        name: rancher
        tasks_from: state.yaml
      tags:
        - start
